### ISSUE TITLE
Investigate writing bindings to a serverless backend

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-net-web/http-service#10]
I'm not sure yet what the right serverless target would be, but I believe one of:
- zeit functions https://zeit.co/blog/introducing-now-rust
- aws lambda https://github.com/awslabs/aws-lambda-rust-runtime
- other platforms?

would probably be worth experimenting with to see if we can bind against.

**Comment by yoshuawuyts** [comment]
Now seems like a pretty straight forward candidate:

__current__
```rust
fn handler(request: http::Request<()>) -> http::Result<http::Response<String>> {
    // Tide code goes here.
    todo!();
}
```

__our interpretation__
```rust
use http_service_now::{Error, Request, Response};

fn handler(request: Request) -> Result<Response, Error> {
    http_service_now::run(MyService)
}
```

__with tide__
```rust
use http_service_now::{Error, Request, Response};
use tide::Tide;

fn handler(request: Request) -> Result<Response, Error> {
    let app = Tide::new();
    app.at("/foo").get(async || "hello world");
    http_service_now::run(app)
}
```

We probably need to wrap things in here somehow inside of a `futures::block_on` call, and I'm not sure yet how to achieve that. But I think it should be feasible!

**Comment by yoshuawuyts** [comment]
Related issue on the AWS side https://github.com/awslabs/aws-lambda-rust-runtime/issues/96

**Comment by secretfader** [comment]
Now that we have the initial version of a Lambda backend, do we want to amend or close this issue? cc @yoshuawuyts

**Comment by yoshuawuyts** [comment]
@secretfader thanks for the ping; I think it's fine to close it! (:
