### ISSUE TITLE
Thoughts on Graceful Shutdown

### ISSUE THREAD

**Issue by mehcode** [rust-net-web/http-service#11]
After a server is started, there needs to exist some way to tell the server that we need to gracefully shutdown. Hyper implements by the user providing a oneshot channel that they can send `()` to to start the shutdown process at any time.

I have a couple ideas:

 * Provide a `into_hyper_service` method that would then enable users to re-implement `serve` but with graceful shutdown.

 * Provide a `serve_until` method that takes in the Receiver end of a oneshot channel (where it then passes it to Hyper).

**Comment by yoshuawuyts** [comment]
@mehcode This is a great idea, thanks for bringing this up!

A few thoughts:
1. we'd probably want to support this in all backends we provide for `http-service` where possible. I think it'd be ideal if we could provide a generic interface for this.
2. graceful shutdown in the general case is not infallible. I'm not sure what the failure mode ought to be (hand indefinitely / return a Result?), but that's probably something we need to think about.

**Comment by yoshuawuyts** [comment]
Closing because we're archiving this repo.
