### ISSUE TITLE
Rename `Fut` into `ResponseFuture`

### ISSUE THREAD

**Issue by prasannavl** [rust-net-web/http-service#24]
Currently, the associated params of `HttpService` are `ConnectionFuture` which corresponds to `connect`, and the `Fut` which corresponds to `respond`. 

I think it'd be better to call this `ResponseFuture` such that it maintains parity. 

`connect` -> `ConnectionFuture`
`respond` -> `ResponseFuture`

rather than the `Fut` that isn't really informative or intuitive.

**Comment by yoshuawuyts** [comment]
I've struggled with this before, and think these changes would indeed add more clarity :+1:.

**Comment by prasannavl** [comment]
PR in :)
