### ISSUE TITLE
Consider renaming `Request` and `Response`

### ISSUE THREAD

**Issue by prasannavl** [rust-net-web/http-service#32]
The `http` crate exports `Request` and `Response`, while the `http-service` exports the exact same names, which are essentially `Request<Body>` and `Response<Body>`. 

While this sounds nice in theory, this gets confusing really quickly, esp while working with upper levels like `tide`. actix-web, for instance uses `HttpRequest`, and `HttpResponse` to solve the same problem, where it's much easier to work with providing clarity. 

Working with `tide` and refactoring it multiple times to experiment, this is one of the biggest annoyances while doing so every time. I guess this could possibly be against the popular opinion, but my personal experience suggests relatable but different names are much easier to work with.  

With that in mind, I'd like to suggest some options to rename:

- `HttpRequest` / `HttpResponse`
- `HttpServiceRequest` / `HttpServiceResponse` 
- `StreamRequest` / `StreamResponse`
- `RequestStream` / `ResponseStream` (Personal favorite)
- `BodyRequest` / `BodyResponse` (doesn't have a ring to it personally, though most accurate)
- `AsyncRequest` / `AsyncResponse` (Hmm)

PS. Personally, I like `Body` as `HttpStream` or `BytesStream` with `RequestStream` and `ResponseStream` as the types.

**Comment by yoshuawuyts** [comment]
> esp while working with upper levels like `tide`.

@prasannavl Do you have an example of where this has lead to confusion? I haven't run into this yet, but admittedly have likely written less tide code than you have. Having a code example motivating this proposal would be very helpful!

**Comment by yoshuawuyts** [comment]
Closing because we're archiving this repo.
