### ISSUE TITLE
How to use HttpService for mutable state?

### ISSUE THREAD

**Issue by rw** [rust-net-web/http-service#42]
The provided example [simple_response.rs](https://github.com/rustasync/http-service/blob/master/examples/simple_response.rs) shows an impl of `HttpServer` that does not modify any internal state.

What is the recommended way to impl an `HttpServer` so that `respond` can modify its internal state?

For example, the `HttpService` could keep a counter of how many times `respond` has been called.

Thanks! :-]

**Comment by Nemo157** [comment]
Use [`Mutex`](https://docs.rs/futures-preview/0.3.0-alpha.17/futures/lock/struct.Mutex.html)/`RwLock` (not yet ported to futures)/[`atomic`](https://doc.rust-lang.org/nightly/std/sync/atomic/index.html) variables (or any other standard synchronization strategy that is futures-aware).

You only get a shared reference as the http server may be invoking your service on multiple requests in parallel.

**Comment by yoshuawuyts** [comment]
Closing because we're archiving this repo.
