### ISSUE TITLE
http-service-lambda v0.3.1 has not been published

### ISSUE THREAD

**Issue by diszone** [rust-net-web/http-service#45]
The only available version in crates.io was v0.1. Nightly rust will refuse to compile because of await! macro. 

But when i try to depend on v0.3.1 cargo will report:
failed to select a version for the requirement `http-service-lambda = "^0.3.1"`

It looks http-service and http-service-hyper have been updated to v0.3.1, but not http-service-lambda. 
Please help to fix it.Thx

**Comment by secretfader** [comment]
[`0.3.1` was published moments ago](https://crates.io/crates/http-service-lambda). Thanks for the report!

cc: @rustasync/maintainers Does it make sense to create an auto-publish workflow for most of the repos in our organization?

**Comment by davidbarsky** [comment]
@secretfader Yep, but I'm not sure of how to set that up. If you do, I'm all ears!

**Comment by secretfader** [comment]
@davidbarsky I sketched out a plan in #46. It shouldn't take long to implement.
