### ISSUE TITLE
Automatically release once CI passes

### ISSUE THREAD

**Issue by secretfader** [rust-net-web/http-service#46]
As suggested in #45, I believe we should automatically publish crates (provided that CI passes on `master`). I'm starting this initiative with `http-service` because it is a foundational tool used by other portions of the async ecosystem, and will help us evaluate the success of automatic releases as a code management practice.

The easiest path forward is to include an [encrypted API token](https://docs.travis-ci.com/user/deployment/cargo/) that Travis will use to automate the release. However, if we plan on moving away from Travis sometime in the future, [`cargo release`](https://github.com/sunng87/cargo-release) could make the process easier.

I propose combining the best elements of each approach: include an encrypted token in `.travis.yml` and let `cargo release` handle the rest.

**Comment by prasannavl** [comment]
I brought this a few months ago; wanted to do this as well. Setting up a CI usually isn't the problem. Think @yoshuawuyts might be able to clarify here.

**Comment by Nemo157** [comment]
The current `dpl` handling only really supports single-crate repos, workspaces need a lot more juggling to get published (especially if they have circular dependencies for examples/tests).

Another part of automated releasing is security of who is able to release. I don't know whether github has tag protection at all, skimming the repo settings it only appears to have branch protection (but I am very unfamiliar with github's org setups so may just be missing something). I got around this on projects where I used to use automated releases by [checking that the tag is signed by an authorized releaser](https://github.com/mycorrhiza/bs58-rs/blob/e426fa9dd8cc4fb64d584ee34b9e8ea367d53431/.travis.yml#L53-L54).

Something that I kept running into was super-minor things breaking the release, like crates.io has a limit of 5 keywords which is impossible to notice before actually attempting to publish.

I eventually gave up on automated releasing for my personal projects, I find it much simpler to make the tag locally, publish it, then push the tag once the publish succeeded; if the publish fails for some reason then I can delete the tag before it is pushed remotely, push a fix for the issue through CI, then try to publish again.

**Comment by yoshuawuyts** [comment]
I'd prefer to keep doing releases by humans; figuring out what the right semver version for a release is cannot be computed automatically in Rust. Unless we start tagging each commit with what kind of change it is (or comparable), at which point I think we're doing extra work to facilitate automation -- which kind of defeats the point.

However adding *some* automation seems like an endeavor worth pursuing. One way to lower friction could be to hook up github actions to chat commands from people with a certain role. Another way of lowering friction would be to make a workspace-aware version bump tool, or patch [`cargo-release`](https://crates.io/crates/cargo-release) to become workspace aware.

**Comment by prasannavl** [comment]
I like the hooking up github actions to chat approach - like cutting in tags each time it's done, and trigger a full auto-publish on that the tags alone. 

While I was for this quite some time ago on `master`, looking back, I think auto-publish just ends up in version bloat with too many unnecessary pre-releases for branches other than specific release tags. 

I prefer the idea of having `pre-$version` or `pre-$datestamp` for pre-releases cut manually and built automatically, rather than publishing master.

**Comment by secretfader** [comment]
I apologize for being absent from the discussion. @Colorado-Gold-Rust had most of my attention for the past month.

@yoshuawuyts suggestion of connecting GitHub actions is probably a good place to begin. Mostly, I wanted to kickstart the discussion with my OP and solicit ideas from other contributors. I wasn't sure if any prior art existed.

As I see it, the primary issue is knowing when a release needs to be cut. We've hit a point where portions of the async ecosystem are being relied upon (even if only by early adopters), which increases the importance of cutting timely releases. When an issue is raised, I've often cut a release. I know that process can be much improved. Who here has access to configure GitHub actions?

I won't deny that semantic commit messages, which can act as configuration for other automated systems, are probably the holy grail of techniques. It's wonderful in theory, but in my opinion, a bit more heavy handed than we have need to be (at least in this stage of the game).

**Comment by yoshuawuyts** [comment]
Closing because we're archiving this repo.
