### ISSUE TITLE
Cannot borrow Request through await

### ISSUE THREAD

**Issue by puckipedia** [rust-net-web/http-service#47]
`Request<Body>` is not `Sync`, which is necessary for `&Request` to be `Send`. This is because `futures_core::stream::Stream` doesn't require `Sync`. This means that passing e.g. `request.uri()` into a separate future and `.await`ing it will mean the entire future is no longer `Send`, and thus cannot be used in basically any generic executor.

**Comment by yoshuawuyts** [comment]
@puckipedia thanks for reporting! -- it sounds as if we'll need to add some more trait bounds probably. Would you be interested in perhaps sharing a test case and/or fix?

Thanks heaps!

**Comment by puckipedia** [comment]
Something like this:

```rust
 async fn frob(url: &Uri) {
     println!("frobbing {:?}", url);
 }

 async fn request(req: Request) -> Result<Response, std::convert::Infallible> {
     frob(req.uri()).await;

     unreachable!();
 }
```

The primary issue is that `Box<dyn Stream<Item = Result<Bytes, Error> + Send + 'static>` isn't Sync. It seems the `hyper` and `lambda` backends are both capable of being `Sync`, so adding a requirement to `Sync` might be reasonable to do. (Also I just noticed `size_hint` isn't implemented on `impl Stream for Body`, so I think `unsafe impl Sync for Body {}` might be safe to do right now; but don't take my word on that, i am not fully awake..)

**Comment by yoshuawuyts** [comment]
Closing because we're archiving this repo.
