### ISSUE TITLE
[http-service-mock] Obtain http_service::Body as Vec<u8> in Response

### ISSUE THREAD

**Issue by cquintana-verbio** [rust-net-web/http-service#53]
I have upgraded my code to Tide 0.4.0, and I cannot write tests that perform requests using the `http-service-mock` crate.

A typical structure of my tests is like the following (which was written for Tide 0.3.0):

```rust
// Initialization
let app = get_app();
let mut server = make_server(app.into_http_service()).unwrap();

// Send request
let body = serde_json::to_string(&body).unwrap();
let req = http::Request::post("/login").body(Body::from(body.as_bytes().to_vec())).unwrap();

// Get response
let res = server.simulate(req).unwrap();
assert_eq!(res.status(), StatusCode::OK);

// Deserialize response
let body = res.into_body().into_vec().await.unwrap(); // NOT WORKING WITH THE NEW VERSION
let response = serde_json::from_str::<LoginResponse>(std::str::from_utf8(&body).unwrap()).expect("Could not parse body.")
assert!(response.session_id.len() > 0, "SessionID must not be empty");
```

The `server.simulate(req).unwrap()` returns a `http_service::Response`, which is a type alias for `http::Response<http_service::Body>`. This `http_service::Body` does not have a direct way of obtaining its contents in a way that can be used directly with serde (as the previous version did), and I'm struggling to find a way to read and parse back my responses.

Is there a new recommended way to do so or has this feature been lost?

**Comment by yoshuawuyts** [comment]
Closing because we're archiving this repo.
