### ISSUE TITLE
Latest release is not pushed to github

### ISSUE THREAD

**Issue by kanru** [rust-net-web/http-service#54]
Hi,

It looks like the following libraries are updated on crates.io but the code is not pushed:

```
http-service = "0.4.0"
http-service-hyper = "0.4.1"
http-service-mock = "0.4.0"
```

and `http-service-lambda` is still `"0.3.1"`

I would like to update `http-service-lambda` to work with the current release, but can't without the latest code in git.

**Comment by yoshuawuyts** [comment]
@kanru it looks like there was a merge conflict somewhere; I've gone ahead and pushed all changes; hope I got it right :crossed_fingers:

**Comment by kanru** [comment]
Thanks! We can close this now.
