### ISSUE TITLE
Update to hyper 0.13

### ISSUE THREAD

**Issue by rofrol** [rust-net-web/http-service#57]
I tried to convert `examples/simple_response.rs` to hyper 0.13 but got stuck at

```
type `ReqBody` is not a member of trait `hyper::service::Service`
```

**Comment by Kilerd** [comment]
I wonder whether this project is abandoned or not. hyper 0.13 has been released for a long time.

**Comment by Kilerd** [comment]
hyper 0.13 had used trait `tower-service::Service` to replace its own `Service` and `MakeService` trait, which is quite simple to use(no more connection things), you can check out https://github.com/hyperium/hyper/blob/master/examples/tower_server.rs for a detailed demo.

**Comment by rofrol** [comment]
Thanks

**Comment by danieleades** [comment]
i think using hyper 0.12 is causing issues downstream in tide.

see https://github.com/http-rs/tide/issues/394

**Comment by yoshuawuyts** [comment]
Closing because we're archiving this repo.
