### ISSUE TITLE
Write docs for http-service-hyper

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-net-web/http-service#8]
Write docs for http-service-hyper.

- [ ] inline docs
- [ ] doc tests
- [ ] readme

**Comment by gruberb** [comment]
Since the last issue with adding docs to `http-service` I have a better idea what's needed and what's happening inside `http-service-hyper`, so I can create a PR for this one as well.

**Comment by yoshuawuyts** [comment]
Closing because we're archiving this repo.
